### PR TITLE
Create m141126_213859_migration_core.php

### PR DESCRIPTION
**Pull request by mdeweerd**
An extension for migrations without a migration for itself?!

Fixed ;-).

### CODE REVIEW

**Comment by cebe** [comment]
well, while it looks like this is useful it will not work as you might expect. The timestamp of the migration is application specific so by adding it to the repo the migration will run in different order for the one that applies it and others that migrate from another point. May not be a big issue but it is unexpected.

Also doing safeUp() in a migration that does schema change will not work in MySQL as it will cause an implicit commit before the migration has finished.

To fix the first problem you may add class called CoreMigration which you extend with an empty migration class in your application that has the correct timestamp.
The second can only be fixed by having two classes or do the transaction stuff manually.

**Comment by mdeweerd** [comment]
1. The timestamp (in the class name) helps ordering migrations, but time of execution is not important for this migration, is it?!  Migrations created after this timestamp will be called later.
   I do not see the issue.
2. I agree that there is an implicit commit, but it is not worse than a "standard" migration.  Hence I do not worry about it.
3. I do not see the need for a fix - the migration worked fine for me (the migration must be applied using the standard migration method).

**Comment by PrplHaz4** [comment]
@mdeweerd table names should respect prefixes also - `{{migration}}` instead of `tbl_migration`

**Comment by mdeweerd** [comment]
@PrplHaz4 The migration table is defined as 'tbl_migration' by default, not with a prefix (see https://github.com/yiisoft/yii/blob/1.1.15/framework/cli/commands/MigrateCommand.php#L44 ).  However, the code can indeed be more generic and take the configuration into account - this is done.
@cebe I moved the migration actions to 'up()' and 'down()'.

**Comment by cebe** [comment]
Merged and added a comment: 9191b9b6624620c3c6a41f0867e06f22e2c77004, thanks!

**Pull request merged**
